model_chat/chat/urls.py
from django.urls import path
from .views import chat_view, LoginView, user_list, upload_file

urlpatterns = [
    path("", LoginView.as_view(template_name="auth/login_page.html"), name="login-user"),
    path("login/", LoginView.as_view(template_name="auth/login_page.html"), name="login-user"),
    path('users/', user_list, name='user_list'),
    path("chat/<str:code>/", chat_view, name="chat-page"),
    path('upload-file/', upload_file, name='upload_file')
]

model_chat/model_chat/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("consumer.urls")),
    path('', include("chat.urls")),
    path('', include("chat_group.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

model_chat/consumer/forms.py
from django import forms
from django.db import transaction

from .models import CustomUser
from .validations import *

class UserForm(forms.Form):

    matricula = forms.IntegerField(
        label='Matrícula',
        widget=forms.NumberInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': 'Matrícula',
        })
    )

    name = forms.CharField(
        label='Nome Completo',
        max_length=255,
        widget=forms.TextInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': 'Nome Completo',
        })
    )

    sexo = forms.ChoiceField(
        label='Sexo',
        choices=CustomUser.SEXO_CHOICES,
        required=False,
        widget=forms.Select(attrs={
            'class': 'form-control mb-3',
        })
    )

    email = forms.EmailField(
        label='Email',
        widget=forms.EmailInput(attrs={
            'class': 'form-control mb-3',
            'placeholder': 'Email',
        })
    )

    photo = forms.ImageField(
        label='Foto',
        required=False,
        widget=forms.FileInput(attrs={
            'class': 'form-control-file',
            'accept': 'image/*',
        })
    )

    def __init__(self, *args, **kwargs):
        
        # Aceitamos a instância do modelo 'CustomUser' como argumento opcional
        self.instance = kwargs.pop('instance', None)
        super().__init__(*args, **kwargs)

        # Se uma instância for passada, populamos o formulário com seus valores
        if self.instance:
            self.fields['name'].initial = self.instance.name
            self.fields['sexo'].initial = self.instance.sexo
            self.fields['email'].initial = self.instance.email
            self.fields['matricula'].initial = self.instance.matricula
            self.fields['photo'].initial = self.instance.photo

    def clean_email(self):
        email = self.cleaned_data.get('email')
        email_unique(email, instance=self.instance)
        return email

    @transaction.atomic
    def save(self, commit=True):

        # Se já houver uma instância, apenas atualize os dados da mesma
        user = self.instance if self.instance else CustomUser()

        # Extraindo dados do formulário e formatando conforme necessário
        matricula_formatting = remove_dot_hyphen_parentheses_espace_formatting(self.cleaned_data['matricula'])

        # Atualizando os campos do usuário
        user.name = self.cleaned_data['name']
        user.sexo = self.cleaned_data['sexo']
        user.email = self.cleaned_data['email']
        user.matricula = matricula_formatting
        user.photo = self.cleaned_data['photo']

        # Salvando o usuário no banco de dados
        if commit:
            user.save()

        return user

model_chat/templates/crud/register_page.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro de Usuário</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h2 class="mb-4 text-center">{% if form.instance.pk %} Atualizar Usuário {% else %} Registro de Usuário {% endif %}</h2>

        <!-- Início do Formulário -->
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-3">
                <label for="id_matricula" class="form-label">Matrícula</label>
                {{ form.matricula }}
            </div>

            <div class="mb-3">
                <label for="id_name" class="form-label">Nome Completo</label>
                {{ form.name }}
            </div>

            <div class="mb-3">
                <label for="id_sexo" class="form-label">Sexo</label>
                {{ form.sexo }}
            </div>

            <div class="mb-3">
                <label for="id_email" class="form-label">Email</label>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label for="id_photo" class="form-label">Foto</label>
                <br>{{ form.photo }}
            </div>

            <!-- Botão de Envio -->
            <button type="submit" class="btn btn-primary">{% if form.instance.pk %} Atualizar {% else %} Registrar {% endif %}</button>
        </form>
        <!-- Fim do Formulário -->

    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>